Repository csjbdd/Gw, pull requests merged in 2022-04, with the labels that each got.

#13 ㅈㅅ
  src/main/java/com/example/gw/services/UserService.java
Labels: 수정

#15 경고구문 일괄수정
  src/main/java/com/example/gw/common/dao/CommonDAOImpl.java
  src/main/java/com/example/gw/common/dao/ICommonDAO.java
  src/main/java/com/example/gw/common/service/CommonServiceImpl.java
  src/main/java/com/example/gw/common/service/ICommonService.java
  src/main/java/com/example/gw/common/util/CommonUtil.java
  src/main/java/com/example/gw/controllers/LoginController.java
  src/main/java/com/example/gw/controllers/RegisterController.java
  src/main/java/com/example/gw/test/DBTestController.java
Labels: 수정

#16 패키지 변경
  src/main/java/com/example/gw/common/service/CommonServiceImpl.java
  src/main/java/com/example/gw/main/controllers/LoginController.java
  src/main/java/com/example/gw/main/controllers/PortletController.java
  src/main/java/com/example/gw/main/controllers/RegisterController.java
  src/main/java/com/example/gw/main/test/DBTestController.java
  src/main/java/com/example/gw/services/UserService.java
Labels: 개선

#17 mapper 경로 수정
  src/main/java/com/example/gw/common/service/CommonServiceImpl.java
  src/main/java/com/example/gw/main/controllers/PortletController.java
  src/main/resources/mappers/testMapper.xml
Labels: 수정

#18 젠킨스 환경변수로 빌드하게하기'
  Jenkins.ProD
Labels: 개선

#20 샘플 템플릿 추가
  src/main/resources/templates/html/404.html
  src/main/resources/templates/html/500.html
  src/main/resources/templates/html/advanced-form-elements.html
  src/main/resources/templates/html/basic-form-elements.html
  src/main/resources/templates/html/blank.html
  src/main/resources/templates/html/chat.html
  src/main/resources/templates/html/collapse.html
  src/main/resources/templates/html/colors.html
  src/main/resources/templates/html/contact.html
  src/main/resources/templates/html/dialogs.html
  src/main/resources/templates/html/events.html
  src/main/resources/templates/html/forgot-password.html
  src/main/resources/templates/html/form-examples.html
  src/main/resources/templates/html/form-upload.html
  src/main/resources/templates/html/form-wizard.html
  src/main/resources/templates/html/list-group.html
  src/main/resources/templates/html/mail-compose.html
  src/main/resources/templates/html/mail-inbox.html
  src/main/resources/templates/html/modals.html
  src/main/resources/templates/html/my-profile.html
  src/main/resources/templates/html/notifications.html
  src/main/resources/templates/html/page-offline.html
  src/main/resources/templates/html/project-list.html
  src/main/resources/templates/html/sign-in.html
  src/main/resources/templates/html/sign-up.html
  src/main/resources/templates/html/sortable-nestable.html
  src/main/resources/templates/html/tabs.html
  src/main/resources/templates/html/taskboard.html
  src/main/resources/templates/html/ticket-list.html
  src/main/resources/templates/html/ui_kit.html
  src/main/resources/templates/html/waves.html
Labels: 추가

#21 샘플페이지 개선
  src/main/java/com/example/gw/main/controllers/SampleController.java
  src/main/resources/templates/CommonTemplate.html
  src/main/resources/templates/layout/meta-data.html
  src/main/resources/templates/sample/sample-header.html
Labels: 개선

#22 샘플컨트롤러 주석수정
  src/main/java/com/example/gw/main/controllers/SampleController.java
Labels: 수정

#23 메인템플릿 분류
  src/main/resources/templates/ui/error/404.html
  src/main/resources/templates/ui/error/500.html
  src/main/resources/templates/ui/pltl/portletMain.html
Labels: 개선

#26 에러컨트롤러 추가
  src/main/java/com/example/gw/common/web/CustomErrorController.java
  src/main/resources/templates/CommonTemplate.html
  src/main/resources/templates/sample/sample.html
Labels: 추가

#28 템플릿 정리 및 로딩바 추가
  src/main/java/com/example/gw/main/controllers/PortletController.java
  src/main/resources/static/assets/bundles/mainscripts.bundle.js
  src/main/resources/static/assets/js/jquery-3.3.1.min.js
  src/main/resources/static/assets/js/pages/pltl/taskboard.js
  src/main/resources/templates/CommonTemplate.html
  src/main/resources/templates/html/blank.html
  src/main/resources/templates/layout/common-import.html
  src/main/resources/templates/sample/sample-header.html
  src/main/resources/templates/ui/pltl/portletHeader.html
  src/main/resources/templates/ui/pltl/portletMain.html
Labels: 개선, 추가
