Repository csjbdd/Gw, pull requests merged in 2022-05, with the labels that each got.

#29 인터셉터 구현진행중
  src/main/java/com/example/gw/common/config/ViewConfig.java
  src/main/java/com/example/gw/common/dao/CommonDAOImpl.java
  src/main/java/com/example/gw/common/dao/ICommonDAO.java
  src/main/java/com/example/gw/common/interceptor/CommonInterCeptor.java
  src/main/java/com/example/gw/common/service/CommonServiceImpl.java
  src/main/java/com/example/gw/common/service/ICommonService.java
  src/main/java/com/example/gw/main/controllers/SampleController.java
  src/main/resources/mappers/MenuMapper.xml
  src/main/resources/static/json/icon.json
  src/main/resources/templates/CommonTemplate.html
  src/main/resources/templates/layout/common-import.html
Labels: 신규

#30 인터셉터 커밋
  src/main/java/com/example/gw/common/dao/CommonDAOImpl.java
  src/main/java/com/example/gw/common/interceptor/CommonInterCeptor.java
  src/main/java/com/example/gw/common/service/CommonServiceImpl.java
  src/main/java/com/example/gw/main/controllers/SampleController.java
  src/main/resources/mappers/MenuMapper.xml
  src/main/resources/templates/CommonTemplate.html
Labels: 문제요청

#32 인터셉터 커밋
  src/main/java/com/example/gw/common/config/ViewConfig.java
  src/main/java/com/example/gw/common/interceptor/CommonInterceptor.java
  src/main/java/com/example/gw/main/controllers/SampleController.java
  src/main/resources/templates/CommonTemplate.html
  src/main/resources/templates/sample/sample.html
Labels: 문제요청

#34 세션관리 공통컨트롤러 구현
  src/main/java/com/example/gw/common/interceptor/CommonInterceptor.java
  src/main/java/com/example/gw/common/web/CommonSessionController.java
Labels: 추가

#35 메뉴 레이아웃 구현
  src/main/java/com/example/gw/common/interceptor/CommonInterceptor.java
  src/main/resources/mappers/MenuMapper.xml
  src/main/resources/templates/layout/aside-left.html
Labels: 개선, 신규

#36 메뉴 레이아웃 수정
  src/main/java/com/example/gw/common/web/CommonSessionController.java
Labels: 수정

#37 ResponseBody & CommonJS 추가
  src/main/java/com/example/gw/main/controllers/LoginController.java
  src/main/resources/static/assets/js/common.js
Labels: 추가

#38 commonPageController 수정
  src/main/java/com/example/gw/common/interceptor/CommonInterceptor.java
  src/main/java/com/example/gw/common/web/CommonPageController.java
Labels: 개선

#39 공통js 경로수정
  src/main/resources/static/js/common/commonAJAX.js
  src/main/resources/static/js/common/commonMenu.js
  src/main/resources/static/js/common/util/_util.js
Labels: 개선

#40 restController 생성 및 메뉴관리 페이지 커밋
  src/main/java/com/example/gw/common/dto/Massage.java
  src/main/java/com/example/gw/common/enums/StatusEnum.java
  src/main/java/com/example/gw/common/web/CommonPageController.java
  src/main/java/com/example/gw/main/restController/MenuManagerRestController.java
  src/main/resources/templates/ui/manager/createMenu.html
  src/main/resources/templates/ui/pltl/portletHeader.html
  src/main/resources/templates/ui/pltl/portletMain.html
  src/main/resources/templates/ui/sample/sample-header.html
  src/main/resources/templates/ui/sample/sample.html
Labels: 개선, 신규

#41 메뉴관리 템플릿 수정
  src/main/java/com/example/gw/common/dto/Massage.java
  src/main/resources/templates/CommonTemplate.html
  src/main/resources/templates/ui/manager/createMenu.html
Labels: 수정

#43 공통 개선
  src/main/resources/static/assets/plugins/nestable/jquery.nestable.js
  src/main/resources/static/js/common/commonMenu.js
  src/main/resources/static/js/manager/createMenu.js
  src/main/resources/templates/CommonTemplate.html
  src/main/resources/templates/layout/common-import.html
  src/main/resources/templates/ui/manager/createMenu.html
Labels: 개선, 신규, 참고

#44 nestable 라이브러리 버전업
  src/main/resources/static/assets/plugins/nestable/jquery.nestable.js
  src/main/resources/static/js/manager/createMenu.js
Labels: 추가

#45 메뉴관리 이벤트 커밋
  src/main/resources/static/assets/plugins/nestable/jquery.nestable.js
  src/main/resources/static/js/manager/createMenu.js
  src/main/resources/templates/ui/manager/createMenu.html
Labels: 수정

#46 메뉴관리 커밋 및 ajax 적용
  src/main/java/com/example/gw/common/dao/CommonDAOImpl.java
  src/main/java/com/example/gw/common/dao/ICommonDAO.java
  src/main/java/com/example/gw/common/service/CommonServiceImpl.java
  src/main/java/com/example/gw/common/service/ICommonService.java
  src/main/java/com/example/gw/common/util/CommonUtil.java
  src/main/java/com/example/gw/main/test/DBTestController.java
  src/main/resources/static/assets/css/style.min.css
  src/main/resources/static/assets/plugins/nestable/jquery.nestable.js
  src/main/resources/static/js/common/commonAJAX.js
  src/main/resources/static/js/manager/createMenu.js
  src/main/resources/templates/layout/common-import.html
  src/main/resources/templates/ui/manager/createMenu.html
Labels: 개선, 추가

#47 공통 alert 커밋
  src/main/resources/static/js/common/commonAlert.js
  src/main/resources/static/js/manager/createMenu.js
Labels: 추가

#48 메뉴관리 커밋
  src/main/java/com/example/gw/main/restController/MenuManagerRestController.java
  src/main/resources/mappers/MenuMapper.xml
  src/main/resources/static/assets/plugins/sweetalert/sweetalert.css
  src/main/resources/static/assets/plugins/sweetalert/sweetalert.min.js
  src/main/resources/static/js/common/commonAlert.js
  src/main/resources/static/js/manager/createMenu.js
  src/main/resources/templates/layout/common-import.html
  src/main/resources/templates/ui/manager/createMenu.html
Labels: 신규

#49 메뉴관리 커밋
  src/main/resources/static/assets/plugins/select2/select2.min.js
  src/main/resources/static/js/common/util/_util.js
  src/main/resources/static/js/manager/createMenu.js
  src/main/resources/static/json/icon.js
  src/main/resources/static/json/icon.json
  src/main/resources/templates/layout/common-import.html
  src/main/resources/templates/ui/manager/createMenu.html
Labels: 개선, 신규

#50 배너변경
  src/main/resources/banner.txt
Labels: 신규

#52 공통재정의 및 메뉴관리 커밋
  src/main/resources/static/js/manager/createMenu.js
  src/main/resources/templates/ui/manager/createMenu.html
Labels: 개선, 신규
